preprocessor_module:
  _target_: third_person_man.preprocess.Preprocessor
  data_path: /data/third_person_manipulation/sim_cube_flipping
  modules:
    robot: ${robot_cfg}
    image: ${image_cfg} # - this is only for tactile training
    # tactile: ${tactile_cfg}
  dump_data_indices: true
  process_single_demo: false

robot_cfg:
  _target_: third_person_man.preprocess.RobotPreprocessor
  subsample_separately: true
  robot_names: ['allegro'] # For simulation we'll only use allegro for now
  robot_thresholds: # If robot thresholds are set to 0 then it will basically not subsample
    hand: 0.005
    # arm: 0.01 # corresponding thresholds to the robot_names
  dump_fingertips: true

image_cfg:
  _target_: third_person_man.preprocess.ImagePreprocessor
  camera_id: 0
  is_ssl: false
  # time_difference: 1 # If the there is no set time difference we will not apply preprocessing for images

tactile_cfg:
  _target_: third_person_man.preprocess.TouchPreprocessor

