trajectory_replay:
  data_path: /data/third_person_manipulation/sim_cube_flipping
  demo_num: 1
  representations: ['image', 'allegro']
  env_cfg: 
    _target_: dexterous_env.cube_flipping_simulation_env.CubeFlippingEnv
    # asset_root: /home/irmak/Workspace/third-person-manipulation/models

fingertip_replay:
  data_path: /data/third_person_manipulation/sim_cube_flipping
  demo_num: 1
  representations: ['image', 'allegro']
  env_cfg: 
    _target_: dexterous_env.fingertip_motion_env.FingertipMotionEnv

base_calibr:
  camera_intrinsics: [[910.45477295,   0.,         648.40692139],
                      [  0.,         910.58001709, 379.32769775],
                      [  0.,          0.,           1.        ]]
  distortion_coefficients: [0., 0., 0., 0., 0.]
  # end_effector_position: [[0,0.02,-0.01]]                      
  # end_effector_position: [[0.0005,-0.0145, -0.0085]]  
  end_effector_position: [[0.0005,-0.0125, -0.0085]]           # End effector position with respect to the marker frame
  end_effector_realignment_matrix: [[0,1,0],[0,0,-1],[-1,0,0]] # Default end effector orientation with respect to base frame
  translation_ratio: 0.22                                      # translation in camera frame / translation in robot fr
  host: '172.24.71.220'
  port: 10005
  calibr_duration: 15
  test_duration: 30
  rvec_calibr: [[2.1737, 0.00045, -0.05424]] 
  tvec_calibr: [[0, -0.02504, 0.20834]]
  # tvec_calibr: None
  # rvec_calibr: None
  eef_to_hand: [[1,0,0,0],
                [0,1,0,0],
                [0,0,1,0],
                [0,0,0,1]]
  save_dir: /media/data/third_person_man/base_frame/22
  replay_dir: /media/data/third_person_man/base_frame/22

fingertip_ik_replay:
  data_path: /data/third_person_manipulation/sim_cube_flipping
  demo_num: 1
  representations: ['image', 'allegro']
  module_name: fingertip_ik_replay
  env_cfg: 
    _target_: dexterous_env.fingertip_motion_env.FingertipMotionEnv
  desired_finger_types: ['middle', 'ring', 'thumb'] 
  trajectory_title: after_debug_middle_ring_thumb

fingertip_ik_tester:
  data_path: /data/third_person_manipulation/sim_cube_flipping
  demo_num: 1
  representations: ['image', 'allegro']
  module_name: fingertip_ik_tester
  num_of_examples: 20
  env_cfg: 
    _target_: dexterous_env.fingertip_motion_env.FingertipMotionEnv
  desired_finger_types: ['middle', 'ring', 'thumb'] 
  plot_name: thumb_fingertip_test
