trajectory_replay:
  data_path: /data/third_person_manipulation/sim_cube_flipping
  demo_num: 1
  representations: ['image', 'allegro']
  env_cfg: 
    _target_: third_person_man.environments.cube_flipping_env.CubeFlippingEnv
    asset_root: /home/irmak/Workspace/third-person-manipulation/models
  